const CATEGORY = {
	FETCH: 'CATEGORY_FETCH',
	FETCH_SUCCESS: 'CATEGORY_FETCH_SUCCESS',
	FETCH_ERROR: 'CATEGORY_FETCH_ERROR',

	FETCH_BEST: 'CATEGORY_BEST_FETCH',
	FETCH_BEST_SUCCESS: 'CATEGORY_BEST_FETCH_SUCCESS',
	FETCH_BEST_ERROR: 'CATEGORY_BEST_FETCH_ERROR',
};

export default CATEGORY;
