const CORE = {
	SAVE_DATA: 'CORE_SAVE_DATA',
	CHANGE_LANGUAGE: 'CORE_CHANGE_LANGUAGE',
	CHANGE_DATE: 'CORE_CHANGE_DATE',

	LOGIN: 'LOGIN',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_ERROR: 'LOGIN_ERROR',

	LOGOUT: 'LOGOUT',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	LOGOUT_ERROR: 'LOGOUT_ERROR',
};

export default CORE;
